# Use an official lightweight Python image
FROM python:3.9-slim  

# Instala aplicações básicas para caso precise vasculhar um contêiner da imagem
RUN apt-get update
RUN apt-get install nano

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

# Set the working directory
WORKDIR /app  

# Copy project files into the container
COPY . /app  

# Instala pacotes Python
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

# Expõe alguns diretórios para o HOST
VOLUME /app/config
VOLUME /app/model


# Expõe para o HOST algumas portas, por padrão
EXPOSE 5000

CMD ["flask", "--app", "app", "run", "--debug"]